#!/usr/bin/python

import gobject
import dbus
import dbus.mainloop.glib
from dbus import ByteArray

def APNProvisioningReceived():
	print "APNProvisioningReceived."
	if canexit:
		mainloop.quit()

if __name__ == '__main__':
	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

	bus = dbus.SystemBus()

	provisioning = dbus.Interface(bus.get_object('org.nemomobile.provisioning', '/'),
						'org.nemomobile.provisioning.interface')

	provisioning.connect_to_signal("APNProvisioningReceived", APNProvisioningReceived)

	s1 = dbus.String("")
	s2 = dbus.String("")
	u1 = dbus.UInt32(0)
	u2 = dbus.UInt32(0)
	i1 = int(0)
	i2 = int(0)
	s3 = dbus.String("")
	f = open('prov.wbxml', 'r')
	content = f.read()
	bytes = ByteArray(content)

	try:
		provisioning.HandleProvisioningMessage(s1,s2,u1,u2,i1,i2,s3,bytes, timeout = 0)
	except dbus.exceptions.DBusException:
		pass

	canexit = True

	mainloop = gobject.MainLoop()
	mainloop.run()
